#!/usr/bin/perl
# vim:ft=perl:et:
use strict;

my $maildir = $ENV{MAILDIR};
my @mails = glob("$maildir/*");

my $output;
if(scalar(@mails > 0)) {
  $output = 'Mail: '. scalar(@mails). ' new';
}
else {
  $output = 'No new mail';
}

print $output;
