# this is where the tagged albums will be copied to
directory: /mnt/music8/+beets_tagged
library:   ~/var/beets/beets.db

plugins: fetchart lyrics missing

missing:
  format: "$path"


import:
  default_action: apply
  duplicate_action: keep
  non_rec_action: ask
  autotag: yes
  move: no


paths:
# $missing added by missing plugin
  default: $albumartist/$albumartist [$year-$month-$day] $album ($format)/$track $title
  singleton: Non-Album/$artist/$artist - $title
  comp: Compilations/$album%aunique{}/$track $title

# To control how tolerant the autotagger is of differences, use the
# strong_rec_thresh option, which reflects the distance threshold below
# which beets will make a “strong recommendation” that the metadata
# be used.
#
# default is 0.04
match:
  strong_rec_thresh: 0.20 
  ignored: missing_tracks unmatched_tracks
  ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray', 'HD-DVD',
                  'VCD', 'SVCD', 'UMD', 'VHS']


ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: blue
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue


#album_fields:
#    format: |
#        formatList = []
#        for item in items:
#            formatList.append(item.format)
#        return formatList
