#!/bin/zsh
# Builtin profiler. Do note that the profiler only profiles functions, not lines
# of code. We can fool it by wrapping stuff up in dummy functions and calling
# them. A work in progress.
#
# To enable the profiler, uncomment the following line and the last one.
#
#zmodload zsh/zprof

# set up some traps (watch out)

TRAPUSR1() { source ~/.zshrc }
TRAPUSR2() { feh -FZrD3 /mnt/Porn/00-pics/ &; exit };

export VIMRUNTIME="$HOME/etc/vim"

for r in $HOME/etc/zsh/*.zsh; do
  if [[ $DEBUG > 0 ]]; then
    echo "zsh: sourcing $r"
  fi
  source $r
done

source $XDG_CONFIG_HOME/zsh/$ZSH_THEME.theme
source $XDG_CONFIG_HOME/zsh/02-abbrevations.zsh

if [[ -f /usr/bin/keychain && -f $HOME/.ssh/id_dsa ]]; then
  eval `keychain --dir $HOME/etc/keychain -q --eval id_dsa`
fi
export TZ='Europe/Stockholm'

# -C will inhibit the check for new completion files, meaning you'll have to
# manually delete .zcompdump or run compinit without -C. The -i flag will skip
# the security check but still check for new completion files. It will ignore
# the insecure files without asking, while -u will use them without asking.
compinit -u
fpath=($XDG_CONFIG_HOME/zsh/compdef $fpath)

compdef _files mkdir
compdef _gnu_generic ln

#zprof
